[theme]
background_color = { r = 255, g = 255, b = 255, a = 255 }
background1_color = { r = 226, g = 227, b = 227, a = 255 }
background2_color = { r = 188, g = 188, b = 188, a = 255 }
background3_color = { r = 127, g = 127, b = 127, a = 255 }
foreground3_color = { r = 122, g = 118, b = 118, a = 255 }
foreground2_color = { r = 100, g = 100, b = 100, a = 255 }
foreground1_color = { r = 75, g = 75, b = 75, a = 255 }
foreground_color = { r = 40, g = 40, b = 40, a = 255 }
input_color = { r = 128, g = 106, b = 217, a = 255 }
output_color = { r = 207, g = 107, b = 35, a = 255 }
available_color = { r = 26, g = 115, b = 232, a = 255 }
interact_color = { r = 231, g = 240, b = 253, a = 255 }
active_color = { r = 0, g = 0, b = 255, a = 255 }
error_color = { r = 255, g = 0, b = 255, a = 255 }
destruction_color = { r = 219, g = 18, b = 18, a = 255 }
augment_color = { r = 135, g = 60, b = 190, a = 255 }
caution_color = { r = 250, g = 222, b = 37, a = 255 }
blueprint_background_color = { r = 250, g = 250, b = 255, a = 255 }
