[theme]
background_color = { r = 0, g = 0, b = 0, a = 255 }
background1_color = { r = 28, g = 26, b = 41, a = 255 }
background2_color = { r = 75, g = 78, b = 94, a = 255 }
background3_color = { r = 116, g = 125, b = 237, a = 255 }
foreground3_color = { r = 122, g = 118, b = 118, a = 255 }
foreground2_color = { r = 148, g = 150, b = 166, a = 255 }
foreground1_color = { r = 232, g = 234, b = 255, a = 255 }
foreground_color = { r = 255, g = 255, b = 255, a = 255 }
input_color = { r = 128, g = 106, b = 217, a = 255 }
output_color = { r = 207, g = 107, b = 35, a = 255 }
available_color = { r = 26, g = 68, b = 161, a = 255 }
interact_color = { r = 253, g = 249, b = 0, a = 255 }
active_color = { r = 212, g = 25, b = 25, a = 255 }
error_color = { r = 255, g = 0, b = 255, a = 255 }
destruction_color = { r = 219, g = 18, b = 18, a = 255 }
augment_color = { r = 135, g = 60, b = 190, a = 255 }
caution_color = { r = 250, g = 222, b = 37, a = 255 }
blueprint_background_color = { r = 10, g = 15, b = 30, a = 255 }

[perf]
blueprint_menu_lod = 0
clipboard_preview_lod = 0
paste_preview_lod = 0
frames_per_tick = 6

[pref]
window_position_size = { x = 0, y = 23, w = 1920, h = 1017 }
ui_scale = 1
toolpane_expanded = 1
show_console = 1
show_properties = 1
min_log_level = 0
selection_preview = 1
